<?php

return [
    'industries' => [
        'AGRICULTURE'                           => 'Agriculture',
        'ARTIFICIAL_INTELLIGENCE Intelligence'  => 'Artificial Intelligence',
        'bUSINESS_TOOLS'                        => 'Business Tools',
        'DIGITAL_MARKETING'                     => 'Digital Marketing',
        'EDUTECH'                               => 'Edutech',
        'FINTECH'                               => 'Fintech',
        'FOOD_BEVERAGE'                         => 'Food / Beverage',
        'HARDWARE'                              => 'Hardware',
        'HEALTHCARE'                            => 'Healthcare',
        'LIFESTYLE'                             => 'Lifestyle',
        'LOGISTICS'                             => 'Logistics',
        'REAL_ESTATE'                           => 'Real Estate',
        'SOFTWARE'                              => 'Software',
        'TRAVEL_TOURISM'                        => 'Travel / Tourism',
        'VENTURE_CAPITAL'                       => 'Venture Capital',
        'OTHER'                                 => 'Other',
    ],

    'countries' => [
        "AF" => "Afghanistan",
        "AX" => "Åland Islands",
        "AL" => "Albania",
        "DZ" => "Algeria",
        "AS" => "American Samoa",
        "AD" => "Andorra",
        "AO" => "Angola",
        "AI" => "Anguilla",
        "AQ" => "Antarctica",
        "AG" => "Antigua and Barbuda",
        "AR" => "Argentina",
        "AM" => "Armenia",
        "AW" => "Aruba",
        "AU" => "Australia",
        "AT" => "Austria",
        "AZ" => "Azerbaijan",
        "BS" => "Bahamas",
        "BH" => "Bahrain",
        "BD" => "Bangladesh",
        "BB" => "Barbados",
        "BY" => "Belarus",
        "BE" => "Belgium",
        "BZ" => "Belize",
        "BJ" => "Benin",
        "BM" => "Bermuda",
        "BT" => "Bhutan",
        "BO" => "Bolivia, Plurinational State of",
        "BQ" => "Bonaire, Sint Eustatius and Saba",
        "BA" => "Bosnia and Herzegovina",
        "BW" => "Botswana",
        "BV" => "Bouvet Island",
        "BR" => "Brazil",
        "IO" => "British Indian Ocean Territory",
        "BN" => "Brunei Darussalam",
        "BG" => "Bulgaria",
        "BF" => "Burkina Faso",
        "BI" => "Burundi",
        "KH" => "Cambodia",
        "CM" => "Cameroon",
        "CA" => "Canada",
        "CV" => "Cape Verde",
        "KY" => "Cayman Islands",
        "CF" => "Central African Republic",
        "TD" => "Chad",
        "CL" => "Chile",
        "CN" => "China",
        "CX" => "Christmas Island",
        "CC" => "Cocos (Keeling) Islands",
        "CO" => "Colombia",
        "KM" => "Comoros",
        "CG" => "Congo",
        "CD" => "Congo, the Democratic Republic of the",
        "CK" => "Cook Islands",
        "CR" => "Costa Rica",
        "CI" => "Côte d'Ivoire",
        "HR" => "Croatia",
        "CU" => "Cuba",
        "CW" => "Curaçao",
        "CY" => "Cyprus",
        "CZ" => "Czech Republic",
        "DK" => "Denmark",
        "DJ" => "Djibouti",
        "DM" => "Dominica",
        "DO" => "Dominican Republic",
        "EC" => "Ecuador",
        "EG" => "Egypt",
        "SV" => "El Salvador",
        "GQ" => "Equatorial Guinea",
        "ER" => "Eritrea",
        "EE" => "Estonia",
        "ET" => "Ethiopia",
        "FK" => "Falkland Islands (Malvinas)",
        "FO" => "Faroe Islands",
        "FJ" => "Fiji",
        "FI" => "Finland",
        "FR" => "France",
        "GF" => "French Guiana",
        "PF" => "French Polynesia",
        "TF" => "French Southern Territories",
        "GA" => "Gabon",
        "GM" => "Gambia",
        "GE" => "Georgia",
        "DE" => "Germany",
        "GH" => "Ghana",
        "GI" => "Gibraltar",
        "GR" => "Greece",
        "GL" => "Greenland",
        "GD" => "Grenada",
        "GP" => "Guadeloupe",
        "GU" => "Guam",
        "GT" => "Guatemala",
        "GG" => "Guernsey",
        "GN" => "Guinea",
        "GW" => "Guinea-Bissau",
        "GY" => "Guyana",
        "HT" => "Haiti",
        "HM" => "Heard Island and McDonald Islands",
        "VA" => "Holy See (Vatican City State)",
        "HN" => "Honduras",
        "HK" => "Hong Kong",
        "HU" => "Hungary",
        "IS" => "Iceland",
        "IN" => "India",
        "ID" => "Indonesia",
        "IR" => "Iran, Islamic Republic of",
        "IQ" => "Iraq",
        "IE" => "Ireland",
        "IM" => "Isle of Man",
        "IL" => "Israel",
        "IT" => "Italy",
        "JM" => "Jamaica",
        "JP" => "Japan",
        "JE" => "Jersey",
        "JO" => "Jordan",
        "KZ" => "Kazakhstan",
        "KE" => "Kenya",
        "KI" => "Kiribati",
        "KP" => "Korea, Democratic People\'s Republic of",
        "KR" => "Korea, Republic of",
        "KW" => "Kuwait",
        "KG" => "Kyrgyzstan",
        "LA" => "Lao People's Democratic Republic",
        "LV" => "Latvia",
        "LB" => "Lebanon",
        "LS" => "Lesotho",
        "LR" => "Liberia",
        "LY" => "Libya",
        "LI" => "Liechtenstein",
        "LT" => "Lithuania",
        "LU" => "Luxembourg",
        "MO" => "Macao",
        "MK" => "Macedonia, the former Yugoslav Republic of",
        "MG" => "Madagascar",
        "MW" => "Malawi",
        "MY" => "Malaysia",
        "MV" => "Maldives",
        "ML" => "Mali",
        "MT" => "Malta",
        "MH" => "Marshall Islands",
        "MQ" => "Martinique",
        "MR" => "Mauritania",
        "MU" => "Mauritius",
        "YT" => "Mayotte",
        "MX" => "Mexico",
        "FM" => "Micronesia, Federated States of",
        "MD" => "Moldova, Republic of",
        "MC" => "Monaco",
        "MN" => "Mongolia",
        "ME" => "Montenegro",
        "MS" => "Montserrat",
        "MA" => "Morocco",
        "MZ" => "Mozambique",
        "MM" => "Myanmar",
        "NA" => "Namibia",
        "NR" => "Nauru",
        "NP" => "Nepal",
        "NL" => "Netherlands",
        "NC" => "New Caledonia",
        "NZ" => "New Zealand",
        "NI" => "Nicaragua",
        "NE" => "Niger",
        "NG" => "Nigeria",
        "NU" => "Niue",
        "NF" => "Norfolk Island",
        "MP" => "Northern Mariana Islands",
        "NO" => "Norway",
        "OM" => "Oman",
        "PK" => "Pakistan",
        "PW" => "Palau",
        "PS" => "Palestinian Territory, Occupied",
        "PA" => "Panama",
        "PG" => "Papua New Guinea",
        "PY" => "Paraguay",
        "PE" => "Peru",
        "PH" => "Philippines",
        "PN" => "Pitcairn",
        "PL" => "Poland",
        "PT" => "Portugal",
        "PR" => "Puerto Rico",
        "QA" => "Qatar",
        "RE" => "Réunion",
        "RO" => "Romania",
        "RU" => "Russian Federation",
        "RW" => "Rwanda",
        "BL" => "Saint Barthélemy",
        "SH" => "Saint Helena, Ascension and Tristan da Cunha",
        "KN" => "Saint Kitts and Nevis",
        "LC" => "Saint Lucia",
        "MF" => "Saint Martin (French part)",
        "PM" => "Saint Pierre and Miquelon",
        "VC" => "Saint Vincent and the Grenadines",
        "WS" => "Samoa",
        "SM" => "San Marino",
        "ST" => "Sao Tome and Principe",
        "SA" => "Saudi Arabia",
        "SN" => "Senegal",
        "RS" => "Serbia",
        "SC" => "Seychelles",
        "SL" => "Sierra Leone",
        "SG" => "Singapore",
        "SX" => "Sint Maarten (Dutch part)",
        "SK" => "Slovakia",
        "SI" => "Slovenia",
        "SB" => "Solomon Islands",
        "SO" => "Somalia",
        "ZA" => "South Africa",
        "GS" => "South Georgia and the South Sandwich Islands",
        "SS" => "South Sudan",
        "ES" => "Spain",
        "LK" => "Sri Lanka",
        "SD" => "Sudan",
        "SR" => "Suriname",
        "SJ" => "Svalbard and Jan Mayen",
        "SZ" => "Swaziland",
        "SE" => "Sweden",
        "CH" => "Switzerland",
        "SY" => "Syrian Arab Republic",
        "TW" => "Taiwan, Province of China",
        "TJ" => "Tajikistan",
        "TZ" => "Tanzania, United Republic of",
        "TH" => "Thailand",
        "TL" => "Timor-Leste",
        "TG" => "Togo",
        "TK" => "Tokelau",
        "TO" => "Tonga",
        "TT" => "Trinidad and Tobago",
        "TN" => "Tunisia",
        "TR" => "Turkey",
        "TM" => "Turkmenistan",
        "TC" => "Turks and Caicos Islands",
        "TV" => "Tuvalu",
        "UG" => "Uganda",
        "UA" => "Ukraine",
        "AE" => "United Arab Emirates",
        "GB" => "United Kingdom",
        "US" =>  "selected United States",
        "UM" => "United States Minor Outlying Islands",
        "UY" => "Uruguay",
        "UZ" => "Uzbekistan",
        "VU" => "Vanuatu",
        "VE" => "Venezuela, Bolivarian Republic of",
        "VN" => "Viet Nam",
        "VG" => "Virgin Islands, British",
        "VI" => "Virgin Islands, U.S.",
        "WF" => "Wallis and Futuna",
        "EH" => "Western Sahara",
        "YE" => "Yemen",
        "ZM" => "Zambia",
        "ZW" => "Zimbabwe",
    ],

    'chinaCities' => [
            "Shanghai",
            "Guangzhou", 
            "Beijing", 
            "Shenzhen", 
            "Nanyang", 
            "Chengdu", 
            "Linyi", 
            "Tianjin", 
            "Shijiazhuang", 
            "Baoding", 
            "Zhoukou", 
            "Weifang", 
            "Wuhan", 
            "Heze", 
            "Ganzhou", 
            "Tongshan", 
            "Handan", 
            "Fuyang", 
            "Jining", 
            "Dongguan", 
            "Chongqing", 
            "Changchun", 
            "Zhumadian", 
            "Ningbo", 
            "Nanjing", 
            "Hefei", 
            "Nantong", 
            "Yancheng", 
            "Foshan", 
            "Nanning", 
            "Hengyang", 
            "Xi\u2019an", 
            "Shenyang", 
            "Tangshan", 
            "Shaoyang", 
            "Changsha", 
            "Zhengzhou", 
            "Zhanjiang", 
            "Cangzhou", 
            "Maoming", 
            "Huanggang", 
            "Xinyang", 
            "Shangrao", 
            "Luoyang", 
            "Bijie", 
            "Yantai", 
            "Quanzhou", 
            "Hangzhou", 
            "Kunming", 
            "Nanchong", 
            "Zunyi", 
            "Lu\u2019an", 
            "Yichun", 
            "Taizhou", 
            "Liaocheng", 
            "Qujing", 
            "Xiangyang", 
            "Qingdao", 
            "Changde", 
            "Dazhou", 
            "Suzhou", 
            "Jieyang", 
            "Nangandao", 
            "Tai\u2019an", 
            "Yulin", 
            "Dezhou", 
            "Suihua", 
            "Qiqihar", 
            "Jinhua", 
            "Shantou", 
            "Weinan", 
            "Suqian", 
            "Suzhou", 
            "Fuzhou", 
            "Zhaotong", 
            "Pudong", 
            "Yongzhou", 
            "Zhangzhou", 
            "Bozhou", 
            "Nanchang", 
            "Xianyang", 
            "Taizhou", 
            "Ji\u2019an", 
            "Mianyang", 
            "Shaoxing", 
            "Yuncheng", 
            "Pingdingshan", 
            "Huai\u2019an", 
            "Xinpu", 
            "Guilin", 
            "Huaihua", 
            "Jiujiang", 
            "Anqing", 
            "Huanglongsi", 
            "Xiaoganzhan", 
            "Changzhou", 
            "Chenzhou", 
            "Wuxi", 
            "Zibo", 
            "Jiaxing", 
            "Dalian", 
            "Yangzhou", 
            "Harbin", 
            "Yibin", 
            "Jiangmen", 
            "Meizhou", 
            "Chifeng", 
            "Guiyang", 
            "Langfang", 
            "Zhangjiakou", 
            "Linfen", 
            "Wenzhou", 
            "Luzhou", 
            "Jiangguanchi", 
            "Neijiang", 
            "Yanjiang", 
            "Yiyang", 
            "Zhaoqing", 
            "Hengshui", 
            "Guigang", 
            "Xiaoxita", 
            "Xiamen", 
            "Chuzhou", 
            "Fuzhou", 
            "Huizhou", 
            "Qingyuan", 
            "Zhuzhou", 
            "Wuhu", 
            "Hechi", 
            "Loudi", 
            "Binzhou", 
            "Liuzhou", 
            "Baojishi", 
            "Guang\u2019an", 
            "Hanzhong", 
            "Zaozhuang", 
            "Anshan", 
            "Deyang", 
            "Lanzhou", 
            "Chengde", 
            "Puyang", 
            "Suining", 
            "Baicheng", 
            "Qincheng", 
            "Taiyuan", 
            "Jinan", 
            "Changzhi", 
            "Shiyan", 
            "Bazhou", 
            "Zhongshan", 
            "Zhenjiang", 
            "\u00dcr\u00fcmqi", 
            "Tongliao", 
            "Heyuan", 
            "Qinzhou", 
            "Xinzhou", 
            "Shaoguan", 
            "Shanwei", 
            "Dingxi", 
            "Ningde", 
            "Putian", 
            "Huzhou", 
            "Wuzhou", 
            "Mudanjiang", 
            "Huludao", 
            "Rizhao", 
            "Nanping", 
            "Longyan", 
            "Hohhot", 
            "Chaozhou", 
            "Weihai", 
            "Sanming", 
            "Luohe", 
            "Lianshan", 
            "Huangshi", 
            "Jiamusi", 
            "Yangjiang", 
            "Yuxi", 
            "Yingkou", 
            "Ma\u2019anshan", 
            "Pingliang", 
            "Gaoping", 
            "Xining", 
            "Jincheng", 
            "Lishui", 
            "Qingyang", 
            "Haikou", 
            "Pingxiang", 
            "Chongzuo", 
            "Jixi", 
            "Wuwei", 
            "Xiping", 
            "Baiyin", 
            "Shengli", 
            "Heihe", 
            "Shuozhou", 
            "Yushan", 
            "Yinchuan", 
            "Jingdezhen", 
            "Zhuhai", 
            "Yucheng", 
            "Xushan", 
            "Guiping", 
            "Zhangjiajie", 
            "Yunfu", 
            "Huangshan", 
            "Huazhou", 
            "Chizhou", 
            "Yutan", 
            "Fuqing", 
            "Yangquan", 
            "Haicheng", 
            "Wuzhong", 
            "Zhangye", 
            "Rucheng", 
            "Shaoyang", 
            "Yangshe", 
            "Yichun", 
            "Yiwu", 
            "Beidao", 
            "Xinyu", 
            "Guankou", 
            "Lianyuan", 
            "Rongcheng", 
            "Kaiyuan", 
            "Zhuji", 
            "Leiyang", 
            "Dadukou", 
            "Yingchuan", 
            "Zhoushan", 
            "Hegang", 
            "Yicheng", 
            "Mizhou", 
            "Taixing", 
            "Xishan", 
            "Zhongwei", 
            "E\u2019zhou", 
            "Xingcheng", 
            "Dongtai", 
            "Yingcheng", 
            "Zhaodong", 
            "Xibeijie", 
            "Huilong", 
            "Luocheng", 
            "Shima", 
            "Meishan", 
            "Nada", 
            "Taihe", 
            "Lhasa", 
            "Dengtalu", 
            "Kaifeng Chengguanzhen", 
            "Hai\u2019an", 
            "Weichanglu", 
            "Leping", 
            "Hailun", 
            "Tongchuan", 
            "Rongjiawan", 
            "Wutong", 
            "Gaoyou", 
            "Yiyang", 
            "Puxi", 
            "Zijinglu", 
            "Xiashi", 
            "Dongyang", 
            "Qingping", 
            "Fuyang", 
            "Zhongba", 
            "Qingnian", 
            "Xinhualu", 
            "Licheng", 
            "Chengguan", 
            "Zunhua", 
            "Shuangqiao", 
            "Langzhong", 
            "Lingbao Chengguanzhen", 
            "Anlu", 
            "Wusong", 
            "Xichang", 
            "Chengxiang", 
            "Dashiqiao", 
            "Changsha", 
            "Shishi", 
            "Miluo Chengguanzhen", 
            "Gaizhou", 
            "Leling", 
            "Jianshe", 
            "Jingcheng", 
            "Xigaz\u00ea", 
            "Shanhu", 
            "Yatou", 
            "Songyang", 
            "Qionghu", 
            "Yanshi Chengguanzhen", 
            "Puyang Chengguanzhen", 
            "Wenchang", 
            "Xiping", 
            "Guixi", 
            "Wuxue", 
            "Xinshi", 
            "Jin\u2019e", 
            "Xinxing", 
            "Suohe", 
            "Zhuangyuan", 
            "Turpan", 
            "Meihekou", 
            "Zhugang", 
            "Tianchang", 
            "Qamdo", 
            "Luocheng", 
            "Shangzhi", 
            "Kuiju", 
            "Fu\u2019an", 
            "Luofeng", 
            "Zhenzhou", 
            "Luanzhou", 
            "Korla", 
            "Wancheng", 
            "Fuding", 
            "Chang\u2019an", 
            "Wencheng", 
            "Aksu", 
            "Ailan Mubage", 
            "Anda", 
            "Yicheng", 
            "Kashgar", 
            "Meicheng", 
            "Chengjiao", 
            "Encheng", 
            "Taozhou", 
            "Dunhua", 
            "Jiaji", 
            "Kaihua", 
            "Jiannan", 
            "Wuhai", 
            "Jinchang", 
            "Xicheng", 
            "Jian\u2019ou", 
            "Minzhu", 
            "Tanbei", 
            "Pingquan", 
            "Ning\u2019an", 
            "Guangming", 
            "Yan\u2019an Beilu", 
            "Hailin", 
            "Lecheng", 
            "Wenlan", 
            "Nagqu", 
            "Fangting", 
            "Zhangjiakou Shi Xuanhua Qu", 
            "Basuo", 
            "Ghulja", 
            "Karamay", 
            "Tieli", 
            "Baicheng", 
            "Lianzhou", 
            "Shihezi", 
            "Helixi", 
            "Huichang", 
            "Zalantun", 
            "Sanya", 
            "Shuanghejiedao", 
            "Yong\u2019an", 
            "Licheng", 
            "Yakeshi", 
            "Lianran", 
            "Tangdong", 
            "Baishan", 
            "Bamiantong", 
            "Yunzhong", 
            "Hotan", 
            "Yakou", 
            "Qianzhou", 
            "Kumul", 
            "Hong\u2019an", 
            "Shaowu", 
            "Linxia Chengguanzhen", 
            "Dongta", 
            "Jinshi", 
            "Beichengqu", 
            "Zhangping", 
            "Wuyishan", 
            "Jiayuguan", 
            "Hunchun", 
            "Ji\u2019an Shi", 
            "Golmud", 
            "Dongning", 
            "Donghua", 
            "Luzhang", 
            "Longjing", 
            "Linjiang", 
            "Fenglu", 
            "Kuytun", 
            "Fukang", 
            "Simao", 
            "Tacheng", 
            "Altay", 
            "Nong\u2019an", 
            "Yunxian Chengguanzhen", 
            "Lucheng", 
            "Tengyue", 
            "Lianhe", 
            "Zhijiang", 
            "Kuqa", 
            "Genhe", 
            "Dali", 
            "Longjiang", 
            "Chongshan", 
            "Mositai", 
            "Boli", 
            "Rongwo", 
            "Hezuo", 
            "Wangqing", 
            "Koktokay", 
            "Linkou", 
            "E\u2019erguna", 
            "Tailai", 
            "Lanxi", 
            "Baiquan", 
            "Zhanggu", 
            "Liuhe", 
            "Chengjiao Chengguanzhen", 
            "Qinggang", 
            "Gannan", 
            "Ma\u2019erkang", 
            "Suileng", 
            "Bayan Hot", 
            "Changling", 
            "Qing\u2019an", 
            "Lindong", 
            "Nenjiang", 
            "Yong\u2019an", 
            "Tangdukou", 
            "Oroqen Zizhiqi", 
            "Alashankou", 
            "Yi\u2019an", 
            "Qarqan", 
            "Tongyangdao", 
            "Kuaidamao", 
            "Xinxing", 
            "Hoh Ereg", 
            "Gy\u00eagu", 
            "Qitai", 
            "Yuanquan", 
            "Gyangz\u00ea", 
            "Gar", 
            "Heyin", 
            "Jinzhong", 
            "Kailu", 
            "Linxi", 
            "Lianhu", 
            "Binhu", 
            "Wulaocun", 
            "Changning", 
            "Yanping", 
            "Dayingmen", 
            "Wuma", 
            "Liuxiang", 
            "Chaowai", 
            "Hongkou", 
            "Changhongjie", 
            "Huancuilou", 
            "Zhangyelu", 
            "Weiyang", 
            "Yangpu", 
            "Dongtundu", 
            "Sanjiang", 
            "Meiyuan Xincun", 
            "Jinrongjie", 
            "Dongjie", 
            "Gulou", 
            "Nanchansi", 
            "Xihu", 
            "Haidian", 
            "Gulou", 
            "Xiaobailou", 
            "Xuhui", 
            "Pingjianglu", 
            "Xincheng", 
            "Chong\u2019ansi", 
            "Chikan", 
            "Luwan", 
            "Rongjiang", 
            "Beidajie", 
            "Fengxian", 
            "Wanghailou", 
            "Gongchen", 
            "Beijie", 
            "Xingguo", 
            "Acheng", 
            "Tiexi", 
            "Xingfulu", 
            "Beijinglu", 
            "Dawangzhuang", 
            "Shuangta", 
            "Tianjiao", 
            "Nanjin", 
            "Jianshelu", 
            "Dayu", 
            "Xiling", 
            "Qianfeng", 
            "Nanjie", 
            "Louqiao", 
            "Shilu", 
            "Shuangling", 
            "Sanyuan Chengguanzhen", 
            "Jinling", 
            "Chenghua", 
            "Shiqiao", 
            "Chengbei", 
            "Jianchang", 
            "Jingshan", 
            "Zhanqian", 
            "Julun", 
            "Qingyang", 
            "Zhifang", 
            "Leicheng", 
            "Zhongyuanlu", 
            "Longzhouwan", 
            "Hongqi", 
            "Bukui", 
            "Xin\u2019an", 
            "Yangjiaping", 
            "Dingping", 
            "Suishan", 
            "Xinshancun", 
            "Liucheng", 
            "Shuimogou", 
            "Nanhang", 
            "Xingfeng", 
            "Shouxihu", 
            "Dongcheng", 
            "Hunjiang", 
            "Xiaoshan", 
            "Enjiang", 
            "Shuangzhong", 
            "Longhua", 
            "Wujiashan", 
            "Wenhe", 
            "Hehai", 
            "Damatou", 
            "Chengnan", 
            "Binhe", 
            "Hanjiang", 
            "Heping", 
            "Shaping", 
            "Qinhong", 
            "Xuri", 
            "Gulou", 
            "Shanhaiguan", 
            "Liminlu", 
            "Lugu", 
            "Xindu", 
            "Ganhechen", 
            "Mingren", 
            "Hutang", 
            "Fengtai", 
            "Xinchenglu", 
            "Helie", 
            "Lubei", 
            "Wenxing", 
            "Yuanzhou", 
            "Anning Xilu", 
            "Heshan", 
            "Yanta", 
            "Xiangyang", 
            "Nankang", 
            "Xianshuigu", 
            "Beilun", 
            "Qindu", 
            "Fangsong", 
            "Dongsheng", 
            "Fulilu", 
            "Dongcheng", 
            "Huayang", 
            "Qujiang", 
            "Huaihelu", 
            "Beijinglu", 
            "Qiaonan", 
            "Chengzhong", 
            "Longshan", 
            "Fengshan", 
            "Chengzhen", 
            "Nanlong", 
            "Jianguo", 
            "Lanjiang", 
            "Dingcheng", 
            "Chang\u2019an", 
            "Zhaobaoshan", 
            "Beilin", 
            "Youyi", 
            "Jinjiazhuang", 
            "Changning", 
            "Pingluo Chengguanzhen", 
            "Mazhang", 
            "Karakax", 
            "Mudan", 
            "Jiekou", 
            "Xiangyang", 
            "Xiyuzhuang", 
            "Jinghai", 
            "Nanzheng Chengguanzhen", 
            "Yili", 
            "Min\u2019an", 
            "Zhongshanlu", 
            "Xucheng", 
            "Ningnan", 
            "Longquan", 
            "Jijiang", 
            "Zhongzhan", 
            "Jiancheng", 
            "Weixian", 
            "Gutao", 
            "Duji", 
            "Xiayang", 
            "Baiguan", 
            "Longxing", 
            "Haicheng", 
            "Xindu", 
            "Suixi", 
            "Ning\u2019an", 
            "Yanliang", 
            "Gucheng", 
            "Baicheng", 
            "Nanwai", 
            "Taiping", 
            "Weitang", 
            "Shunde", 
            "Aoyang", 
            "Zhuyang", 
            "Qingyuan", 
            "Xinhu", 
            "Guitang", 
            "Huohua", 
            "Zhongshan Donglu", 
            "Liyang", 
            "Furong Beilu", 
            "Yulong", 
            "Nu\u2019erbage", 
            "Daishan", 
            "Wenlin", 
            "Luyang", 
            "Decheng", 
            "Zhengdonglu", 
            "Suizhong", 
            "Jiangyan", 
            "Langchi", 
            "Shengli", 
            "Jia Xian Chengguanzhen", 
            "Songling", 
            "Fendou", 
            "Ganting", 
            "Fenghua", 
            "Yujin", 
            "Wuyuan", 
            "Yuecheng", 
            "Xiaodian", 
            "Liulin", 
            "Shuidong", 
            "Jingning Chengguanzhen", 
            "Huolu", 
            "Jibenggang",
            "Longcheng",
            "Fendou",
            "Jiulong",
            "Wenhua",
            "Dongcheng",
            "Xianfeng",
            "Yichuan Chengguanzhen",
            "Wujin",
            "Xincheng",
            "Yangming",
            "Cuntan",
            "Chongyang",
            "Labu",
            "Yunmeng Chengguanzhen",
            "Xiwai",
            "Luoning Chengguanzhen",
            "Suicheng",
            "Caidian",
            "Ningyang",
            "Chaoge",
            "Wuquan",
            "Fengtai Chengguanzhen",
            "Hongjunlu",
            "Tianpeng",
            "Xinan",
            "Lishu",
            "Liangshan",
            "Guoyang Chengguanzhen",
            "Yutian",
            "Pucheng Chengguanzhen",
            "Taihe",
            "Kaiping",
            "Yueyang",
            "Guanshan",
            "Longquan",
            "Zhenping Chengguanzhen",
            "Dingcheng",
            "Jiaxiang",
            "Niushan",
            "Yanta",
            "Baixi",
            "Hanfeng",
            "Guangming",
            "Yanjin Chengguanzhen",
            "Zhaoxian",
            "Jiangkou",
            "Huarong Chengguanzhen",
            "Yaozhou",
            "Dongdajie",
            "Pingnan",
            "Gaoyao",
            "Nan\u2019an",
            "Yancheng",
            "Longnan",
            "Longcheng",
            "Song Xian Chengguanzhen",
            "Taohuajiang",
            "Tubu",
            "Daokou",
            "Haimen",
            "Yuecheng",
            "Linquan Chengguanzhen",
            "Tongchuan",
            "Rizhao",
            "Daming",
            "Zhongzhou",
            "Lin\u2019an",
            "Guixi",
            "Yancheng Chengguanzhen",
            "Chicheng",
            "Xiushan",
            "Lihou",
            "Ninghai",
            "Hanshang",
            "Xinmian",
            "Duohu",
            "Lucheng",
            "Danzhu",
            "Hecheng",
            "Huaiyang Chengguanzhen",
            "Poyang",
            "Bishui",
            "Erqu",
            "Yankou",
            "Pitong",
            "Lanshan",
            "Zhangguizhuang",
            "Shengli",
            "Tangxing",
            "Huojia Chengguanzhen",
            "Wangyue",
            "Wangkui",
            "Fengcheng",
            "Jiyuanlu",
            "Xingsha",
            "Liquan Chengguanzhen",
            "Lechang",
            "Jinsha",
            "Linping",
            "Yanling",
            "Huazhou",
            "Chonglong",
            "Runing",
            "Binhe",
            "Zhaoyu",
            "Yishan",
            "Xiangdong",
            "Puyang",
            "Anxi",
            "Gongjiang",
            "Bencheng",
            "Lianjiang",
            "Changtu",
            "Jizhou",
            "Tiantai Chengguanzhen",
            "Dongzhen",
            "Chenyang",
            "Gaotangling",
            "Chunxi",
            "Guantao",
            "Nuojiang",
            "Guoyuan Xincun",
            "Xin\u2019an Chengguanzhen",
            "Danxi",
            "Anren Chengguanzhen",
            "Guozhen",
            "Nanxi",
            "Songlong",
            "Yongfeng",
            "Yanji",
            "Xincheng",
            "Xigang",
            "Tiancheng",
            "Yunyang",
            "Hejiang",
            "Licheng",
            "Wuhe Chengguanzhen",
            "Kaijiang",
            "Wansheng",
            "Fengqiu Chengguanzhen",
            "Chengjiang",
            "Fuying",
            "Nanjie",
            "Dengzhou",
            "Dizhuang",
            "Yunling",
            "Yuanyang Chengguanzhen",
            "Guhan",
            "Chengwu",
            "Gunan",
            "Luozhou",
            "Qingyuan",
            "Deqing",
            "Luhua",
            "Gushi Chengguanzhen",
            "Xiayi Chengguanzhen",
            "Emin",
            "Haimen",
            "Dahuaishu",
            "Lufeng",
            "Daying",
            "Jinniu",
            "Fengcheng",
            "Dongguan",
            "Yong\u2019an",
            "Fufeng",
            "Weicheng",
            "Wenshang",
            "Jing\u2019an",
            "Loushanguan",
            "Peicheng",
            "Tiantang",
            "Renminlu",
            "Hongqiao",
            "Taikang Chengguanzhen",
            "Weishi Chengguanzhen",
            "Yelin",
            "Baiyashi",
            "Ningling Chengguanzhen",
            "Fangcheng Chengguanzhen",
            "Nanchangshan",
            "Mingxing",
            "Jincheng",
            "Nanzhou",
            "Taiqian Chengguanzhen",
            "Yunxi",
            "Fengxian",
            "Huili Chengguanzhen",
            "Dazhong",
            "Yingshang Chengguanzhen",
            "Funan Chengguanzhen",
            "Mianchi Chengguanzhen",
            "Ningjin",
            "Tongxu Chengguanzhen",
            "Nanhai",
            "Shedian",
            "Xuyang",
            "Dong\u2019an",
            "Yanqing",
            "Baofeng Chengguanzhen",
            "Anxiang",
            "Daiyue",
            "Xiongzhou",
            "Taocheng",
            "Yisuhe",
            "Quanjiang",
            "Shishan",
            "Cuifeng",
            "Yancheng",
            "Yushan",
            "Hexi",
            "Linquan",
            "Baoyou",
            "Fengxiang Chengguanzhen",
            "Gul\u00fc",
            "Xin\u2019anjiang",
            "Xun Xian Chengguanzhen",
            "Zitong",
            "Sangyuan",
            "Gangu Chengguanzhen",
            "Xingpinglu",
            "Penglai",
            "Lingcheng",
            "Cuijiang",
            "Wuchang",
            "Doucun",
            "Dianbu",
            "Anling",
            "Shoushan",
            "Quyang",
            "Wuyun",
            "Fuyu",
            "Jinxiang",
            "She Xian",
            "Yingshouyingzi",
            "Hede",
            "Dongshan",
            "Zhangjiang",
            "Tangxiang",
            "Jiaocheng",
            "Guhuai",
            "Tangyang Chengguanzhen",
            "Xiedian",
            "Qincheng",
            "Qishan",
            "Jingchuan Chengguanzhen",
            "Yishi",
            "Fugou Chengguanzhen",
            "Fangzheng",
            "Gaocun",
            "Jincheng",
            "Qiaotou",
            "Rushan",
            "Renhe",
            "Toqsu",
            "Tianchi",
            "Daqinglu",
            "Xing\u2019an",
            "Yancheng",
            "Xiguan",
            "Zherong",
            "Sanhe",
            "Luyuan",
            "Shacheng",
            "Bayinsai",
            "Binhe",
            "Handian",
            "Zhenyang",
            "Sui\u2019an",
            "Jiuquan",
            "Taohong",
            "Xipu",
            "Mengjin Chengguanzhen",
            "Dawu Chengguanzhen",
            "Luoshan Chengguanzhen",
            "Lucheng",
            "Jinggan",
            "Qianquan",
            "Huangpi",
            "Longquan",
            "Xiaoxi",
            "Hanshou",
            "Gongjing",
            "Tianning",
            "Liyang",
            "Shiqiao",
            "Qi Xian Chengguanzhen",
            "Gucheng Chengguanzhen",
            "Dongkou",
            "Zhecheng Chengguanzhen",
            "Nanle Chengguanzhen",
            "Chaling Chengguanzhen",
            "Youxian Chengguanzhen",
            "Xuyong",
            "Shangpai",
            "Zhoukou",
            "Juye",
            "Rongcheng",
            "Shangli",
            "Xi Xian Chengguanzhen",
            "Kunyang",
            "Nancheng",
            "Pumiao",
            "Shangguan",
            "Bobai",
            "Chaicun",
            "Fengcheng",
            "Douhudi",
            "Zhushan Chengguanzhen",
            "Pingchuan",
            "Qingfu",
            "Jianjun",
            "Hanyuan",
            "Lukou",
            "Hancheng",
            "Jiang\u2019an",
            "Minjian",
            "Wenbi",
            "Donghegumiao",
            "Shunling",
            "Lankao Chengguanzhen",
            "Juancheng",
            "Shucheng Chengguanzhen",
            "Wufeng",
            "Dezhou",
            "Wenping",
            "Fengcheng",
            "Xidu",
            "Gaohe",
            "Dingtao",
            "Meijiang",
            "Xinzhai",
            "Junyang",
            "Yanghe",
            "Chujiang",
            "Languan",
            "Xinjia",
            "Yangying",
            "Zhijin",
            "Xinning",
            "Beiyuan",
            "Jinxi",
            "Sicheng",
            "Niangxi",
            "Guiyang Chengguanzhen",
            "Mingzhou",
            "Luoyang",
            "Lingchuan",
            "Pingdu",
            "Tongcheng",
            "Xincheng",
            "Zhangwan",
            "Xunzhong",
            "Chengzhong",
            "Yuncheng",
            "Zhonghe",
            "Shinan",
            "Changning",
            "Xunchang",
            "Yongxing Chengguanzhen",
            "Zishui",
            "Liulinzhou",
            "Heping",
            "Qingfeng Chengguanzhen",
            "Taihe Chengguanzhen",
            "Huarong",
            "Neihuang Chengguanzhen",
            "Fuji",
            "Dongcheng",
            "Rongcheng",
            "Tancheng",
            "Poskam",
            "Longcheng",
            "Ducheng",
            "Lingjiang",
            "Longde Chengguanzhen",
            "Baicheng",
            "Qinting",
            "Lingcheng",
            "Linjiang",
            "Huicheng",
            "Puji",
            "Salaqi",
            "Guancheng",
            "Yunxixian Chengguanzhen",
            "Liujiaxia",
            "Leping",
            "Pingpo",
            "Xing\u2019an",
            "Nanjiang",
            "Xiangcheng Chengguanzhen",
            "Dunhou",
            "Shengrenjian",
            "Luogang",
            "Shouchun",
            "Qingquan",
            "Linli",
            "Dongguang",
            "Lingcheng",
            "Sui Xian Chengguanzhen",
            "Nanma",
            "Jinchuan",
            "Yuzhong Chengguanzhen",
            "Leiyang",
            "Zhongmu Chengguanzhen",
            "Dingchang",
            "Wacheng",
            "Quanzhou",
            "Jifeng",
            "Guangrao",
            "Zhangcheng",
            "Xixiang",
            "Dongcun",
            "Qianling",
            "Sunjia Buzi",
            "Dongshan",
            "Huaicheng",
            "Naxi",
            "Tonghe",
            "Xiangfeng",
            "Xincheng",
            "Huayuan",
            "Echeng",
            "Huaibin Chengguanzhen",
            "Jinyuan",
            "Dazhe",
            "Xujiang",
            "Gounan",
            "Tuojiang",
            "Lintong",
            "Xicheng",
            "Baoshan",
            "Chuimatan",
            "Hanyin Chengguanzhen",
            "Fengming",
            "Luocheng", 
            "Yunji", 
            "L\u00fceyang Chengguanzhen", 
            "Hengdong Chengguanzhen", 
            "Ruyang Chengguanzhen", 
            "Chenying", 
            "Zhaozhen", 
            "Weiyuan", 
            "Tafeng", 
            "Pan\u2019an", 
            "Meilu", 
            "Kuangyuan", 
            "Lianfeng", 
            "Zhongshu", 
            "Xinmatou", 
            "Jianghai", 
            "Kongjiazhuang", 
            "Tianyi", 
            "Mengshan", 
            "Suicheng", 
            "Donghe", 
            "Hekou", 
            "Panlong", 
            "Jinchuan", 
            "Xingguo", 
            "Taicheng", 
            "Yongchang", 
            "Jingzhou", 
            "Dawa", 
            "Chengxi", 
            "Wenchang", 
            "Youxi", 
            "Hengzhou", 
            "Guzhen Chengguanzhen", 
            "Xincheng", 
            "Shangcheng Chengguanzhen", 
            "Huagai", 
            "Khutubi", 
            "Huoqiu Chengguanzhen", 
            "Dingcheng", 
            "Qiaoxu", 
            "Ningxiang", 
            "Chengxiang", 
            "Xiushui", 
            "Nan\u2019an", 
            "Liyuan", 
            "Dajie", 
            "Guangzhoulu", 
            "Nanjie", 
            "Songyuan", 
            "Jingchuan", 
            "Chaigoubu", 
            "Xinzheng", 
            "Yanqi", 
            "Songyuan", 
            "Yangxin", 
            "Yitiaoshan", 
            "Xinguan", 
            "Huanfeng", 
            "Yong\u2019an", 
            "Minqing", 
            "Yongle", 
            "Jishi", 
            "Dongcheng", 
            "Zhuolu", 
            "Fengyang Fuchengzhen", 
            "Guidong Chengguanzhen", 
            "Chunhua", 
            "Guyang", 
            "Bashan", 
            "Jicheng", 
            "Fucheng", 
            "Linxi", 
            "Shuangfengqiao", 
            "Rucheng Chengguanzhen", 
            "Beidaihe", 
            "Huidong", 
            "Shancheng", 
            "Jishan", 
            "Neixiang Chengguanzhen", 
            "Longxian Chengguanzhen", 
            "Wenfeng", 
            "Dangchang Chengguanzhen", 
            "Lincheng", 
            "Lishu", 
            "Yangshuo", 
            "Mugala", 
            "Cili", 
            "Fengyi", 
            "Dongluqiao", 
            "Zhangbei", 
            "Chaoyang", 
            "Beijie", 
            "Junlian", 
            "Xinshiba", 
            "Liaogao", 
            "Hanji", 
            "Longxu", 
            "Hezheng Chengguanzhen", 
            "Awat", 
            "Nanzhao", 
            "Lin\u2019an", 
            "Shule", 
            "Kuancheng", 
            "Shahejie", 
            "Chengxiang", 
            "Jiangkou", 
            "Maoping", 
            "Yunxing", 
            "Yuhai", 
            "Lingxi", 
            "Maytagh", 
            "Jingping", 
            "Hong\u2019an Chengguanzhen", 
            "Shayang", 
            "Aral", 
            "Dingcheng", 
            "Tantang", 
            "Hezhang", 
            "Matou", 
            "Jincheng", 
            "Lop", 
            "Suonan", 
            "Fucheng", 
            "Datong", 
            "Nanzhao Chengguanzhen", 
            "Hanchang", 
            "Lufu", 
            "Hongmiao", 
            "Fan Xian Chengguanzhen", 
            "Kaihua Chengguanzhen", 
            "Haoxue", 
            "Yinying", 
            "Zhaoren", 
            "Yuanling", 
            "Mianyang", 
            "Fengzhou", 
            "Zhangjiapan", 
            "Nancun", 
            "Shaping", 
            "Dianjun", 
            "Kaiyun", 
            "Gujiang", 
            "Gulaobei", 
            "Xiangjiaba", 
            "Mingshui", 
            "Aoyang", 
            "Huanan", 
            "Fuyang", 
            "Fenyi", 
            "Changbai", 
            "Wulingyuan", 
            "Zhouning", 
            "Langao Chengguanzhen", 
            "Guanghe Chengguanzhen", 
            "Dingbian", 
            "Yuelai", 
            "Jingpeng", 
            "Yuxi", 
            "Xinhua", 
            "Zijin", 
            "Muxi", 
            "Tiantan", 
            "Gushu", 
            "Xunyi Chengguanzhen", 
            "Nanpi", 
            "Datian", 
            "Huliao", 
            "Mulan", 
            "Shazhou", 
            "Songyang", 
            "Sanhe", 
            "Mingyue", 
            "Anju", 
            "Yuli", 
            "Tuojiang", 
            "Weifen", 
            "Pingma", 
            "Aoxi", 
            "Gutian", 
            "Yizhang Chengguanzhen", 
            "Yantan", 
            "Jiangle", 
            "Yuanba", 
            "Fushi", 
            "Zhangjiachuan", 
            "Guangming", 
            "Chengxiang", 
            "Fancheng", 
            "Pucheng", 
            "Lintan Chengguanzhen", 
            "Chengxian Chengguanzhen", 
            "Xinji", 
            "Lushi Chengguanzhen", 
            "Kangping", 
            "Sanchahe", 
            "Dianyang", 
            "Haiyang", 
            "Jiahe Chengguanzhen", 
            "Huayuan", 
            "Xincheng", 
            "Zhangfeng", 
            "Luzhai", 
            "Pisha", 
            "Gulin", 
            "Qiangezhai", 
            "Xiangcheng", 
            "Fusui", 
            "Lincheng", 
            "Gantang", 
            "Longquan", 
            "Longgang", 
            "Zhongshan", 
            "Yongqing", 
            "Xinglong", 
            "Haishiwan", 
            "Luanchuan Chengguanzhen", 
            "Xin\u2019an", 
            "Yuanshan", 
            "Zhongba", 
            "Yiyang Chengguanzhen", 
            "Biyang", 
            "Meixi", 
            "Huixian Chengguanzhen", 
            "Wuxue Shi", 
            "Nanzhang Chengguanzhen", 
            "Zhongshu", 
            "Kunyang", 
            "Shilu", 
            "Quyang", 
            "Xiangkou", 
            "Wanzhi", 
            "Micheng", 
            "Mucheng", 
            "Dahua", 
            "Xiaoduchuan", 
            "Huayuan", 
            "Zhongcheng", 
            "Chongwen", 
            "Pucheng", 
            "Lianzhou", 
            "Shijiao", 
            "Rongshui", 
            "Jingyang", 
            "Aksu", 
            "Guyi", 
            "Changshun", 
            "Chang\u2019an", 
            "Zhushan", 
            "Ziyang Chengguanzhen", 
            "Weichang", 
            "Juanshui", 
            "Tuncheng", 
            "Fusong", 
            "Anyang", 
            "Shanhe", 
            "Tengzhou", 
            "Mingfeng", 
            "Wuling", 
            "Jingyang", 
            "Jichang", 
            "Luxi", 
            "Gaotai Chengguanzhen", 
            "Wuxuan", 
            "Xiaojiang", 
            "Sanjiang", 
            "Yitong", 
            "Dayou", 
            "Siyang", 
            "Huangyuan Chengguanzhen", 
            "Dafeng", 
            "Qinglong", 
            "Fengshan", 
            "Donghuang", 
            "Xinshui", 
            "Lushar", 
            "Qianyang Chengguanzhen", 
            "Yaofeng", 
            "Mabai", 
            "Lindian", 
            "Yuanma", 
            "Jingyu", 
            "Donglan", 
            "Qinhe", 
            "Tiandiba", 
            "Yixing", 
            "Gulang", 
            "Longquan", 
            "Temuli", 
            "Huangzhai", 
            "Xilin", 
            "Rifeng", 
            "Huangshan", 
            "Bayan", 
            "Gongcheng", 
            "Aletengxire", 
            "Huangmei", 
            "Yongbei", 
            "Qinjiang", 
            "Miyang", 
            "Fenggang", 
            "Kangle", 
            "Dongping", 
            "Xihuachi", 
            "Yongdeng Chengguanzhen", 
            "Xiluodu", 
            "Zhaxi", 
            "Qingfenglin", 
            "Loufan", 
            "Jinjiang", 
            "Chaotian", 
            "Weizhou", 
            "Lishan", 
            "Xinhuang", 
            "Xiugu", 
            "Kangbao", 
            "Zhenyuan Chengguanzhen", 
            "Luoxiong", 
            "Hechuan", 
            "Zhouqu Chengguanzhen", 
            "Tianzhou", 
            "Tianfu", 
            "Yilong", 
            "Xisa", 
            "Longquan", 
            "Zhongcheng", 
            "Gaoleshan", 
            "Jiading", 
            "Zhonghualu", 
            "Wumahe", 
            "Dabu", 
            "Dongchuan", 
            "Miaodong", 
            "Mali", 
            "Dongliang\u2019erzhuang", 
            "Lishi", 
            "Guangze", 
            "Zhong\u2019an", 
            "Pingle", 
            "Jiaokui", 
            "Longquan", 
            "Huafeng", 
            "Yongning", 
            "Luqiao", 
            "Linjiang", 
            "Zoumachang", 
            "Pingshan", 
            "Xiaopingba", 
            "Fenghuang", 
            "Bama", 
            "Sankoutang", 
            "Longhua", 
            "Chicheng", 
            "Baiquan", 
            "Duru", 
            "Shuangjiang", 
            "Qasq", 
            "Shancheng", 
            "Dangcheng", 
            "Fengning", 
            "Yezhou", 
            "Zhuozishan", 
            "Machang", 
            "Fengyi", 
            "Hengshui", 
            "Fangxian Chengguanzhen", 
            "Dailing", 
            "Yining", 
            "Menglang", 
            "Xiwanzi", 
            "Liaoyang", 
            "Yuelejie", 
            "Jinping", 
            "Xinning", 
            "Tongquan", 
            "Yisa", 
            "Luntai", 
            "Renhua", 
            "Changning", 
            "Jiangna", 
            "Siyang", 
            "Gangou", 
            "Gufeng", 
            "Xuefeng", 
            "Baokang Chengguanzhen", 
            "Yanjing", 
            "Ziyang", 
            "Yinggen", 
            "Jinhe", 
            "Ningzhou", 
            "Sicheng", 
            "Shuiying", 
            "Yujiazhai", 
            "Guji", 
            "Xinglongchang", 
            "Niupizhai", 
            "Bagrax", 
            "Yuyue", 
            "Xiuwu Chengguanzhen", 
            "Gedong", 
            "Xinjie", 
            "Bao\u2019an", 
            "Magitang", 
            "Qingyuan", 
            "Rende", 
            "Tiandeng", 
            "Aihua", 
            "Xincheng", 
            "Qingyang", 
            "Pingxiang", 
            "Guwei", 
            "Xiangzhou", 
            "Fengchuan", 
            "Guyang", 
            "Long\u2019an", 
            "Dongmen", 
            "Meixian", 
            "Jincheng", 
            "Youdian", 
            "Shawan", 
            "Guanyang", 
            "Wanshan", 
            "Xincheng Chengguanzhen", 
            "Huishi", 
            "Tuanfeng", 
            "Ning\u2019er", 
            "Bujie", 
            "Danfeng", 
            "Tantou", 
            "Longsheng", 
            "Aba", 
            "Debao Chengguanzhen", 
            "Sunwu", 
            "Huaiyuan Chengguanzhen", 
            "Bianjiang", 
            "Daliyuan", 
            "Jinshan", 
            "Dongping", 
            "Tongbai Chengguanzhen",
            "Xinhua",
            "Longtoushan Jiezi",
            "Shuigou\u2019ao",
            "Pingyuan",
            "Xiqu",
            "Baocheng",
            "Yaodu",
            "Lijiang",
            "Jinshan",
            "Peyziwat",
            "Huanggexi",
            "Jinshi",
            "Cuihua",
            "Guangrao",
            "Menghai",
            "Yanjing",
            "Longchuan",
            "Yongding",
            "Gaojiacun",
            "Guishan",
            "Baiyang",
            "Jimsar",
            "Jinbi",
            "Yuquan",
            "Wuqi",
            "Si\u2019en",
            "Zhaoping",
            "Daojiang",
            "Taoyang",
            "Jiecun",
            "Linwu Chengguanzhen",
            "Nandan Chengguanzhen",
            "Tianxingchang",
            "Shuitianzhai",
            "Changpu",
            "Mengcheng Chengguanzhen",
            "Gengma",
            "Hobor",
            "Zuitai",
            "Tiexianxi",
            "N\u00eadong",
            "Sanguanzhai",
            "Lianzhu",
            "Wulan",
            "Yuhu",
            "Chuansiba",
            "Xinjing",
            "Zhedao",
            "Laojie",
            "Wenquan",
            "Luojiang",
            "Huazangsi",
            "Xiaopu",
            "Xiaping",
            "Fengcheng",
            "Yilan",
            "Taocheng",
            "Jiecun",
            "Nansha",
            "Jinping",
            "Xuri",
            "Togrog Ul",
            "Yancheng",
            "Qinghua",
            "Honggang",
            "Daxing",
            "Zhujiacun",
            "Daihai",
            "Jinchang",
            "Liulin",
            "Xuejiawan",
            "Shuangshipu",
            "Nanzhao",
            "Inder",
            "Uchturpan",
            "Yongfu",
            "Shuimo",
            "Xinghe Chengguanzhen",
            "Tokkuztara",
            "Daxing",
            "Nanjian",
            "Taikang",
            "Shangjie",
            "Qiaowa",
            "Mengdong",
            "Jinhua",
            "Shanjiao",
            "Sanjiang",
            "Xinjie",
            "Longshan",
            "Liangdang Chengguanzhen",
            "Jiezishang",
            "Laodianzi",
            "Jinping",
            "Hongwansi",
            "Qili",
            "Yacha",
            "Longbo",
            "Ulan Hua",
            "Jianning",
            "Goujie",
            "Hekou",
            "Lanyi",
            "Qiancheng",
            "Leidaba",
            "Longgang",
            "Shangba",
            "Lingcheng",
            "Maoshanjie",
            "Baokang",
            "Laojie",
            "Guye",
            "Gonghe",
            "Doushaguan",
            "Xingguo",
            "Chengfangqiao",
            "Dedang",
            "Yueyang",
            "Fucheng",
            "Shirong",
            "Chensan",
            "Beishan",
            "Shanzidi",
            "Gecheng",
            "Liancheng",
            "Xiangshui",
            "Qiaoshang",
            "Yongding",
            "Qianyou",
            "Huquan",
            "Dasongshu",
            "Lizhi",
            "Shuitou",
            "Zhongxin",
            "Xinfa",
            "Xishaqiao",
            "Liupai",
            "Nayun",
            "Yunhe",
            "Shuangxi",
            "Meilin",
            "Jinding",
            "Jianxincun",
            "Dongxing",
            "Laojiezi",
            "Lingquan",
            "Shiziba",
            "Zhihe",
            "Gaolan Chengguanzhen",
            "Mengmeng",
            "Zhonghechang",
            "Aitianba",
            "Zhongcun",
            "Xiangyang",
            "Hepingyizu",
            "Xilin",
            "Baiyin Chagan",
            "Tongle",
            "Tongyang",
            "Moshiyi",
            "Nahaping",
            "Sujiaying",
            "Yongchang Chengguanzhen",
            "Tianshan",
            "Beiyingzi",
            "Xincun",
            "Tieyingzi",
            "Zhenlai",
            "Tekes",
            "Ziyuan",
            "Zagunao",
            "Dongfeng",
            "Tuquan",
            "Ganzi",
            "Jin\u2019an",
            "Wanhechang",
            "Taipingdian",
            "Hanyuan",
            "Lubei",
            "Gufu",
            "Jiuchenggong",
            "Zongyang",
            "Yuping",
            "Fuyu",
            "Yuanjiazhuang",
            "Dianweijie",
            "Haomen",
            "Laojiezi",
            "Laofangzi",
            "Muzeng",
            "Yopurga",
            "Nilka",
            "Furong",
            "Huamachi",
            "Hanbin",
            "Jiezi",
            "Baohe",
            "Songbai",
            "Muping",
            "Changping",
            "Sanlei",
            "Tuodian",
            "Yinla",
            "Haliut",
            "Mengsuo",
            "Panlian",
            "Namka",
            "Xindou",
            "Shangpa",
            "Weiyuan",
            "Huangjingba",
            "Xiaotiechang",
            "Enle",
            "Wenxian Chengguanzhen",
            "Shangtianba",
            "Xinling",
            "Jiaoxiyakou",
            "Fengshan",
            "Wuxi",
            "Shuigou",
            "Labuleng",
            "Nansan",
            "Qingquan",
            "Xianghu",
            "Xinyuan",
            "Dongqu",
            "Wufeng",
            "Pengjia Zhaizi",
            "Longzhou",
            "Sangpi",
            "Zuitou",
            "Gaocheng",
            "Kouqian",
            "Daqin Tal",
            "Shimen",
            "Long\u2019an Chengxiangzhen",
            "Jinta",
            "Napo Chengxiangzhen",
            "Nanpiao",
            "Rulin",
            "Tangyuan",
            "Pujiawan",
            "Leli",
            "Jinshan",
            "Mengla",
            "Xianshui",
            "Chengguan",
            "Jinxiu",
            "Quxar",
            "Liuba",
            "Qabqa",
            "Wudan",
            "Shuangjiang",
            "Qiongxi",
            "Chatang",
            "Minquan Chengguanzhen",
            "Menglie",
            "Nankengzai",
            "Rulong",
            "Kulun",
            "Nagqu",
            "Daban",
            "Qingkou",
            "Saziba",
            "Tarrong",
            "Jiantang",
            "Sanjiaocheng",
            "Qapqal",
            "Kaji",
            "Qiaozhuang",
            "Hoxut",
            "Hexi",
            "Songmai",
            "Tongzilin",
            "Babao",
            "Tongyu",
            "Meilisi",
            "Luanping",
            "Jinzhu",
            "Shangtang",
            "Gabasumdo",
            "Meixing",
            "Norbukyungz\u00ea",
            "Bainang",
            "Dianga",
            "Duchang",
            "Pagnag",
            "Namling",
            "Xiaqiaotou",
            "Hejing",
            "Xing\u2019an",
            "Luhua",
            "Batang",
            "Fuliang",
            "Uliastai",
            "Chenggan",
            "Caohe",
            "Luxu",
            "Niya",
            "Duolun",
            "Maizhokunggar",
            "Zaindainxoi",
            "Qira",
            "Guma",
            "Jianshe",
            "Xiasi",
            "Xangda",
            "Gengqing",
            "Jimai",
            "Mashan",
            "Cikai",
            "Kaiwen",
            "Konggar",
            "Ramai",
            "Chinggil",
            "Hekou",
            "Yumen",
            "Zequ",
            "Hekou",
            "Toksun",
            "Geluwan",
            "Jiangzhou",
            "Puting",
            "Y\u00eandum",
            "Q\u00fcx\u00fc",
            "Xia\u2019er",
            "Rangke",
            "Gyitang",
            "Lh\u00fcnz\u00ea",
            "Shuibian",
            "Xiayang",
            "Biru",
            "Samdo",
            "Ming\u2019antu",
            "Dangquka",
            "Damxung",
            "Biancheng",
            "Qamq\u00eanxoi",
            "Xinyuan",
            "D\u00eaq\u00ean",
            "Ningshan Chengguanzhen",
            "Nyinma",
            "Qianguo",
            "X\u00eagar",
            "Zito",
            "Bayan Huxu",
            "Baima",
            "Bailingmiao",
            "Seke",
            "Ziketan",
            "Chumba",
            "Moluo",
            "Molo",
            "Khuma",
            "Xireg",
            "S\u00earaitang",
            "Meishan",
            "Fengxiang",
            "Gartog",
            "Hongshui",
            "Wangda",
            "Xinli",
            "Racaka",
            "Dazhasi",
            "Qonggyaixoi",
            "Kalpin",
            "Fendou",
            "Youganning",
            "Domartang",
            "Coka",
            "Qusum",
            "Nongchangbalian",
            "Zhaosu",
            "Zhuxi Chengguanzhen",
            "Sahuteng",
            "Gyaij\u00eapozhangg\u00ea",
            "Dabancheng",
            "Xin Bulag",
            "Akqi",
            "Burqin",
            "Zhamog",
            "Saihan Tal",
            "D\u00eangq\u00ean",
            "Nangxian",
            "Kangmar",
            "Urho",
            "Chuqung",
            "Bengshutang",
            "G\u00eading",
            "Yuegai",
            "Jomda",
            "Nixia",
            "Bieligutai",
            "Tungdor",
            "Nanggarz\u00ea",
            "Juegang",
            "Shengping",
            "Xiasima",
            "Rongmei",
            "Chaoyang",
            "Shiquanhe",
            "Dartang",
            "Laxi",
            "Ulan",
            "Dawu",
            "Mainling",
            "Shuguang",
            "Sa\u2019gya",
            "Nierong",
            "Wucheng",
            "Baishan",
            "M\u00eadog",
            "Yanshou",
            "Xarlung",
            "Gyamotang",
            "Ri\u2019ngoin",
            "Huzhong",
            "Damxoi",
            "Lh\u00fcnzhub",
            "Xayar",
            "Gyangkar",
            "Mangqu",
            "Shiguai",
            "Huichang",
            "Gangba",
            "Ngamring",
            "Kambaxoi",
            "Zhongcun",
            "Qian\u2019an",
            "Ruoqiang",
            "Lazanzhong",
            "Lixin Chengguanzhen",
            "Hongliuwan",
            "Wenquan",
            "Xinlin",
            "Congd\u00fc",
            "Baiyu",
            "Hongshan",
            "Mandalt",
            "Dalain Hob",
            "Chugq\u00eansumdo",
            "Pagq\u00ean",
            "Zhowagoin",
            "Gyigang",
            "Burang",
            "Qajort\u00eabu",
            "Ehen Hudag",
            "Youhao",
            "Zhad\u00fcn",
            "Shaliuhe",
            "Bala Ga\u2019er Gaole",
            "Zhize",
            "Zongga",
            "Pubu",
            "Sangri",
            "Dangchengwan",
            "Shangdu",
            "Qagan Us",
            "Machali",
            "Luring",
            "Gangsha",
            "Toding",
            "Binzhou",
            "Maindong",
            "Geji",
            "Lumaka",
            "Lhozhag",
            "Zhabu",
            "S\u00earkang",
            "Zangkaxa",
            "Xagmakajor",
            "Qumod\u00ea",
            "Rutog",
            "Langjiu",
            "Shahe",
            "Jisegumen",
            "Toli",
            "Xoixar",
            "Xilinji",
    ]
];